# Site settings
title: Grubby theme
name: Disjfa valours
email: disjfa@disjfa.com
description: >
  A simple theme, responsive and beautiful. For useage on your own product.
  It has a lot of example use cases you can implement on your own website.
baseurl: "/grubby-theme"
url: "https://disjfa.github.io"
github_url:  https://github.com/disjfa/grubby-theme
github_username:  disjfa
github_base: /tree/master/site/

# Google
google_analytics: UA-83598448-1

# Build settings
markdown: kramdown

# deployment
source: site
host: 0.0.0.0
port: 5000
